version: '3.8'
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask-app
    restart: always

  flask-app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - bento-service
    restart: always

  bento-service:
    build: .
    ports:
      - "3000:3000"
    restart: always
