
{% extends bento_base_template %}
{% block SETUP_BENTO_BASE_IMAGE %}
FROM --platform=linux/amd64 python:3.10-slim

WORKDIR /bento
# Copy and install Python dependencies
COPY requirements.txt /bento/
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt

COPY modelPackaging/ /bento/modelPackaging/
COPY app/ /bento/app/

{{ super() }}

{% endblock %}